// data.js — Voorbeeld-data voor het ImpactHub-prototype.
// Alles is fictief en bedoeld om de app te laten leven. De echte app zou
// deze data uit een database halen. Hier zit het in het geheugen en wordt
// (waar nodig) opgeslagen in localStorage via store.js.

window.SEED = {
  // De ingelogde gebruiker. In dit prototype "ben jij" deze persoon.
  // Je kunt het profiel aanpassen; wijzigingen worden bewaard in je browser.
  currentUserId: 'u-me',

  users: [
    {
      id: 'u-me',
      name: 'Jij',
      headline: 'Fondsenwerver · op zoek naar nieuwe impact',
      role: 'Fondsenwerver',
      org: '',
      location: 'Nederland',
      color: '#0e7c66',
      about: 'Welkom op ImpactHub! Pas dit profiel aan via de knop "Profiel bewerken". Vertel kort wie je bent, voor welk doel je je hard maakt en waar je goed in bent.',
      skills: ['Fondsenwerving', 'Donateurbinding', 'Storytelling'],
      openToWork: true,
      connectionIds: ['u-2', 'u-4', 'u-7'],
    },
    {
      id: 'u-2',
      name: 'Saskia de Vries',
      headline: 'Hoofd Fondsenwerving bij Natuur & Co',
      role: 'Hoofd Fondsenwerving',
      org: 'Natuur & Co',
      location: 'Utrecht',
      color: '#2563eb',
      about: 'Al 12 jaar bouw ik aan duurzame donateurrelaties. Specialist in grote giften (major donors) en nalatenschappen. Altijd in voor een goed gesprek over de toekomst van geven.',
      skills: ['Major Donors', 'Nalatenschappen', 'Relatiebeheer', 'Strategie'],
      openToWork: false,
      connectionIds: ['u-me', 'u-3', 'u-5', 'u-8'],
    },
    {
      id: 'u-3',
      name: 'Mehmet Yilmaz',
      headline: 'Campagneleider bij Stichting Schoon Water',
      role: 'Campagneleider',
      org: 'Stichting Schoon Water',
      location: 'Rotterdam',
      color: '#db2777',
      about: 'Ik vertaal complexe thema’s naar campagnes die mensen raken én aanzetten tot actie. Trots op onze laatste actie die 4.300 nieuwe donateurs opleverde.',
      skills: ['Campagnemanagement', 'Social Media', 'Mobilisatie', 'Copywriting'],
      openToWork: false,
      connectionIds: ['u-2', 'u-6'],
    },
    {
      id: 'u-4',
      name: 'Anouk Bakker',
      headline: 'Vrijwilligerscoördinator bij Buurtkracht',
      role: 'Vrijwilligerscoördinator',
      org: 'Buurtkracht',
      location: 'Groningen',
      color: '#ea580c',
      about: 'Vrijwilligers zijn het kloppend hart van elke goede-doelenorganisatie. Ik werf, begeleid en behoud ze met plezier. Warme overdracht boven alles.',
      skills: ['Vrijwilligersbeleid', 'Werving', 'Training', 'Community'],
      openToWork: false,
      connectionIds: ['u-me', 'u-7'],
    },
    {
      id: 'u-5',
      name: 'Tomás Oliveira',
      headline: 'Directeur bij Kind Centraal',
      role: 'Directeur',
      org: 'Kind Centraal',
      location: 'Den Haag',
      color: '#7c3aed',
      about: 'Bestuurder met hart voor kinderrechten. Ik geloof in transparantie, meetbare impact en het lef om dingen anders te doen. We zoeken altijd talent dat dat deelt.',
      skills: ['Leiderschap', 'Governance', 'Impactmeting', 'Pleitbezorging'],
      openToWork: false,
      connectionIds: ['u-2', 'u-8'],
    },
    {
      id: 'u-6',
      name: 'Linda Janssen',
      headline: 'Grant Writer & Subsidie-expert',
      role: 'Grant Writer',
      org: 'Freelance',
      location: 'Eindhoven',
      color: '#0891b2',
      about: 'Ik schrijf winnende subsidieaanvragen voor goede doelen. Vorig jaar samen €1,2 mln aan fondsen opgehaald voor cliënten. Open voor nieuwe opdrachten.',
      skills: ['Subsidieaanvragen', 'Vermogensfondsen', 'Rapportage', 'Budgettering'],
      openToWork: true,
      connectionIds: ['u-3'],
    },
    {
      id: 'u-7',
      name: 'David Okafor',
      headline: 'Donor Relations Officer bij Hoop Wereldwijd',
      role: 'Donor Relations',
      org: 'Hoop Wereldwijd',
      location: 'Amsterdam',
      color: '#16a34a',
      about: 'Elke donateur verdient een persoonlijk bedankje. Ik bouw aan loyaliteitsprogramma’s die geven leuk maken. Fan van data én van een handgeschreven kaartje.',
      skills: ['Donateurbinding', 'CRM', 'E-mailmarketing', 'Loyaliteit'],
      openToWork: false,
      connectionIds: ['u-me', 'u-4'],
    },
    {
      id: 'u-8',
      name: 'Fatima El Amrani',
      headline: 'Manager Corporate Partnerships bij GroenDoel',
      role: 'Partnership Manager',
      org: 'GroenDoel',
      location: 'Utrecht',
      color: '#ca8a04',
      about: 'Ik koppel bedrijven aan maatschappelijke doelen waar ze écht warm voor lopen. Win-win-partnerschappen met langetermijnimpact zijn mijn handelsmerk.',
      skills: ['Bedrijfspartnerschappen', 'Sponsoring', 'Onderhandelen', 'MVO'],
      openToWork: false,
      connectionIds: ['u-2', 'u-5'],
    },
  ],

  posts: [
    {
      id: 'p-1',
      authorId: 'u-3',
      time: Date.now() - 1000 * 60 * 60 * 2,
      text: 'We hebben het geflikt! 🎉 Onze "Druppel voor Druppel"-campagne haalde in zes weken 4.300 nieuwe maandelijkse donateurs binnen. Drie lessen: 1) één helder verhaal verslaat tien losse feiten, 2) laat de doelgroep zelf aan het woord, 3) bedank sneller dan je gewend bent. Trots op het hele team. 💧',
      tags: ['campagne', 'fondsenwerving'],
      likedBy: ['u-2', 'u-7', 'u-8'],
      comments: [
        { id: 'c-1', authorId: 'u-2', time: Date.now() - 1000 * 60 * 90, text: 'Gefeliciteerd! Dat bedank-punt onderschatten zoveel organisaties.' },
      ],
    },
    {
      id: 'p-2',
      authorId: 'u-6',
      time: Date.now() - 1000 * 60 * 60 * 6,
      text: 'Subsidie-tip van de week: begin je aanvraag nooit met je organisatie, maar met het probleem dat de fondsverstrekker wil oplossen. Spiegel hun taal, hun doelen, hun jaarverslag. Je aanvraag moet voelen als het antwoord op hún vraag. Werkt elke keer weer. 📝',
      tags: ['subsidie', 'tip'],
      likedBy: ['u-2', 'u-3', 'u-5'],
      comments: [],
    },
    {
      id: 'p-3',
      authorId: 'u-5',
      time: Date.now() - 1000 * 60 * 60 * 26,
      text: 'Vandaag publiceerden we ons impactrapport. Geen mooie verhalen zonder cijfers, geen cijfers zonder de verhalen erachter. 18.000 kinderen bereikt, en we laten precies zien hoe. Transparantie is geen marketing — het is respect voor wie ons mogelijk maakt. Link in de comments.',
      tags: ['impact', 'transparantie'],
      likedBy: ['u-2', 'u-8'],
      comments: [
        { id: 'c-2', authorId: 'u-8', time: Date.now() - 1000 * 60 * 60 * 25, text: 'Hier kunnen veel organisaties van leren. Petje af.' },
      ],
    },
    {
      id: 'p-4',
      authorId: 'u-4',
      time: Date.now() - 1000 * 60 * 60 * 48,
      text: 'Op zoek naar 15 vrijwilligers voor onze najaarsactie in Groningen. 🙌 Geen ervaring nodig, wél een warm hart en twee handen. Ken jij iemand? Tag diegene hieronder. Samen krijgen we de buurt in beweging.',
      tags: ['vrijwilligers', 'werving'],
      likedBy: ['u-7'],
      comments: [],
    },
  ],

  jobs: [
    {
      id: 'j-1',
      title: 'Senior Fondsenwerver Particulieren',
      org: 'Natuur & Co',
      location: 'Utrecht (hybride)',
      type: 'Fulltime',
      category: 'Fondsenwerving',
      posted: Date.now() - 1000 * 60 * 60 * 20,
      salary: '€3.800 – €4.600 p/m',
      description: 'Jij bouwt aan langdurige relaties met onze particuliere donateurs en major donors. Ervaring met nalatenschappen is een pré. Je werkt nauw samen met campagne en data.',
    },
    {
      id: 'j-2',
      title: 'Campagnemedewerker Digitaal',
      org: 'Stichting Schoon Water',
      location: 'Rotterdam',
      type: 'Fulltime',
      category: 'Campagne',
      posted: Date.now() - 1000 * 60 * 60 * 50,
      salary: '€3.100 – €3.700 p/m',
      description: 'Van concept tot conversie: jij zet online campagnes neer die mensen in beweging brengen. Je kent je weg in social ads, e-mailflows en A/B-testen.',
    },
    {
      id: 'j-3',
      title: 'Coördinator Vrijwilligers',
      org: 'Buurtkracht',
      location: 'Groningen',
      type: 'Parttime (24u)',
      category: 'Vrijwilligers',
      posted: Date.now() - 1000 * 60 * 60 * 72,
      salary: '€2.900 – €3.300 p/m (o.b.v. fulltime)',
      description: 'Werf, begeleid en behoud onze groeiende groep vrijwilligers. Jij bent het warme gezicht van de organisatie en zorgt dat iedereen op de juiste plek schittert.',
    },
    {
      id: 'j-4',
      title: 'Grant Writer (freelance opdracht)',
      org: 'Kind Centraal',
      location: 'Remote',
      type: 'Freelance',
      category: 'Subsidies',
      posted: Date.now() - 1000 * 60 * 60 * 5,
      salary: 'In overleg',
      description: 'We zoeken een ervaren schrijver voor drie grote subsidieaanvragen dit kwartaal. Aantoonbaar succes bij vermogensfondsen is een harde eis.',
    },
    {
      id: 'j-5',
      title: 'Manager Corporate Partnerships',
      org: 'GroenDoel',
      location: 'Utrecht (hybride)',
      type: 'Fulltime',
      category: 'Partnerschappen',
      posted: Date.now() - 1000 * 60 * 60 * 96,
      salary: '€4.200 – €5.200 p/m',
      description: 'Jij smeedt strategische allianties met bedrijven die onze missie willen versterken. Commercieel inzicht én een hart voor de zaak gaan bij jou hand in hand.',
    },
  ],

  events: [
    {
      id: 'e-1',
      title: 'Nationale Dag van de Fondsenwerving',
      date: '2026-06-18',
      org: 'Goede Doelen Nederland',
      location: 'Spant! Bussum',
      attendees: 240,
    },
    {
      id: 'e-2',
      title: 'Webinar: Nalatenschappen voor beginners',
      date: '2026-06-05',
      org: 'Natuur & Co Academy',
      location: 'Online',
      attendees: 96,
    },
    {
      id: 'e-3',
      title: 'Meetup Vrijwilligerscoördinatoren Noord',
      date: '2026-06-12',
      org: 'Buurtkracht',
      location: 'Groningen',
      attendees: 38,
    },
  ],

  // Thema's / goede doelen die "trending" zijn — voor de rechterkolom.
  causes: [
    { tag: 'Klimaat & Natuur', count: 1280 },
    { tag: 'Kinderrechten', count: 940 },
    { tag: 'Armoedebestrijding', count: 870 },
    { tag: 'Gezondheid', count: 760 },
    { tag: 'Dierenwelzijn', count: 610 },
  ],
};
